name: Metrics (isocalendar only)

on:
  schedule: [{cron: "0 0 * * 1"}]  # Atualiza toda segunda
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          colors: "blue"  # muda o esquema para tons verdes
